# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fundementals of Game Dev Course
email: bruh@bruh.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for IUST Fundementals of Game Development Fall 2021 Course
baseurl: "/game-course-fall-2021" # the subpath of your site, e.g. /blog
url: "http://amuuu.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
